WebApplication2/WebApplication2/Controllers/AspNetRoleUserController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplication2.Models;

namespace WebApplication2.Controllers
{

    //[Authorize(Roles = "Admin,Faculty")]
    public class AspNetRoleUserController : Controller
    {
        private SEP24Team3Entities db = new SEP24Team3Entities();

        // GET: AspNetRoles/Create
        public ActionResult Create(string roleId)
        {
            ViewBag.Role = db.AspNetRoles.Find(roleId);
            var userInRole = db.AspNetUsers.Where(x => x.AspNetRoles.Any(g => g.Id == roleId)); // Find user exists in roleId
            var userNotInRole = db.AspNetUsers.Except(userInRole); // Get user not in userInRole
            ViewBag.Users = new SelectList(userNotInRole, "Id", "UserName");
            return View();
        }

        // POST: AspNetRoles/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(string roleId, string userId)
        {
            var role = db.AspNetRoles.Find(roleId);
            var user = db.AspNetUsers.Find(userId);
            role.AspNetUsers.Add(user);
            db.Entry(role).State = EntityState.Modified;
            db.SaveChanges();

            return RedirectToAction("Index", "AspNetRoles");
        }


        [HttpGet]
        public ActionResult Edit(string userId)
        {
            ViewBag.User = db.AspNetUsers.Find(userId);
            ViewBag.Role = new SelectList(db.AspNetRoles, "Id", "Name");
            return View();
        }


        [HttpPost]
        public ActionResult Edit(string roleId, string userId)
        {
            var user = db.AspNetUsers.Find(userId);
            var role = db.AspNetRoles.Find(roleId);
            role.AspNetUsers.Add(user);
            db.Entry(role).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index", "AspNetRoles");
        }

        // GET: AspNetRoles/Delete/5
        public ActionResult Delete(string roleId, string userId)
        {
            var role = db.AspNetRoles.Find(roleId);
            var user = db.AspNetUsers.Find(userId);
            role.AspNetUsers.Remove(user);
            db.Entry(role).State = EntityState.Modified;
            db.SaveChanges();

            return RedirectToAction("Index", "AspNetRoles");
        }




        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebApplication2/WebApplication2/Views/AspNetRoleUser/Create.cshtml
@using WebApplication2.Models;
@{
    ViewBag.Title = "Create";
    var Role = ViewBag.Role as AspNetRole;
    var Users = ViewBag.Users as SelectList;
    var db = new SEP24Team3Entities();
    var user = db.AspNetUsers.ToList();

}

<h2>Create</h2>



@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Add User to @Role.Name</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })


        <div class="form-group">
            @Html.Label("User", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("UserId", Users, new { @class = "form-control chosen" })
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Add" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    <a href="@Url.Action("Index","AspNetRoles")">Back to List</a>
</div>

@section scripts{
    <script>
        $(function () {
            $(".chosen").chosen();
        });
    </script>

}

WebApplication2/WebApplication2/Views/AspNetRoleUser/Delete.cshtml
@model WebApplication2.Models.AspNetRole
@using WebApplication2.Models
@{
    ViewBag.Title = "Delete";
    var userId = ViewBag.UserId as AspNetUser;
    var db = new SEP24Team3Entities();
}



<h3>Are you sure you want to delete this?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            Name
        </dt>

        <dd>
            @userId.UserName
        </dd>

    </dl>

    @using (Html.BeginForm("Delete", "AspNetRoleUser", FormMethod.Post))
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="text" style="display:none;" name="roleId" value="@Model.Id" />
            <input type="text" style="display:none;" name="userId" value="@userId.Id" />
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            <a class="btn btn-dark" href="@Url.Action("Index","AspNetRoles")">Back</a>
        </div>
    }
</div>

WebApplication2/WebApplication2/Views/AspNetRoleUser/Edit.cshtml
@using WebApplication2.Models;
@{
    ViewBag.Title = "Edit";
    var Role = ViewBag.Role as SelectList;
    var user = ViewBag.User as AspNetUser;
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">      
        <hr />
        <h4>Update Role for @user.UserName</h4>
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })


        <div class="form-group">
            @Html.Label("Role", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("roleId", Role, new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    <a href="@Url.Action("Index","AspNetRoles")">Back to List</a>
</div>