WebApplication2/WebApplication2/Controllers/ClassesController.cs
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.Entity;
using System.Data.OleDb;
using System.Data.SqlClient;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplication2.Libs;
using WebApplication2.Models;

namespace WebApplication2.Controllers
{
    [Authorize]
    public class ClassesController : Controller
    {
        private SEP24Team3Entities db = new SEP24Team3Entities();

        // GET: Classes
        public ActionResult Index()
        {
            var classes = db.Classes.Include(x => x.AspNetUser).Include(x => x.FACULTY).Include(x => x.SEMESTER);
            return View(classes.ToList());
        }

        [Authorize(Roles = "Lecturer")]
        public ActionResult Index2() // View Of Lecturer
        {
            var lecturerId = User.Identity.GetUserId();
            var classesOfLecturer = db.Classes.Where(x => x.Userid == lecturerId).ToList();
            return View(classesOfLecturer);
        }

        public ActionResult Index3(string userId) // View of Student
        {
            ViewBag.USER_ID = db.AspNetUsers.FirstOrDefault(x => x.Id == userId);
            var studentInfo = db.AspNetUsers.FirstOrDefault(x => x.Id == userId);
            var classOfStudent = db.Classes.Where(x => x.ClassLists.Any(g => g.Student.StudentCode.Equals(studentInfo.UserCode)));
            return View(classOfStudent.ToList());
        }

        //// GET: Classes/Details/5
        //public ActionResult Details(int id)
        //{
        //    var @class = db.Classes.Find(id);

        //    //var classStudents = db..Include(c => c.Class).Include(c => c.Student);
        //    //return View(classStudents.ToList());
        //    return View(@class.ClassLists.ToList());
        //}

        // GET: Classes/Create
        public ActionResult Create()
        {
            ViewBag.UserId = new SelectList(db.AspNetUsers.Where(x => x.AspNetRoles.Any(g => g.Name.Equals("Lecturer"))), "Id", "Email");
            //ViewBag.Userid = new SelectList(db.AspNetUsers, "Id", "Email");
            ViewBag.Facultyid = new SelectList(db.FACULTies, "ID", "FACULTYNAME");
            ViewBag.Semesterid = new SelectList(db.SEMESTERs, "ID", "SEMESTER_CODE");
            return View();
        }

        // POST: Classes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Class @class)
        {
            if (ModelState.IsValid)
            {
                db.Classes.Add(@class);
                db.SaveChanges();
                return RedirectToAction("Index");
            }


            ViewBag.UserId = new SelectList(db.AspNetUsers.Where(x => x.AspNetRoles.Any(g => g.Name.Equals("Lecturer"))), "Id", "Email");
            //ViewBag.Userid = new SelectList(db.AspNetUsers, "Id", "Email", @class.Userid);
            ViewBag.Facultyid = new SelectList(db.FACULTies, "ID", "FACULTYNAME", @class.Facultyid);
            ViewBag.Semesterid = new SelectList(db.SEMESTERs, "ID", "SEMESTER_CODE", @class.Semesterid);
            return View(@class);
        }

        // GET: Classes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Class @class = db.Classes.Find(id);
            if (@class == null)
            {
                return HttpNotFound();
            }

            ViewBag.UserId = new SelectList(db.AspNetUsers.Where(x => x.AspNetRoles.Any(g => g.Name.Equals("Lecturer"))), "Id", "Email");
            //ViewBag.Userid = new SelectList(db.AspNetUsers, "Id", "Email", @class.Userid);
            ViewBag.Facultyid = new SelectList(db.FACULTies, "ID", "FACULTYNAME", @class.Facultyid);
            ViewBag.Semesterid = new SelectList(db.SEMESTERs, "ID", "SEMESTER_CODE", @class.Semesterid);
            return View(@class);
        }

        // POST: Classes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Class @class)
        {
            if (ModelState.IsValid)
            {
                db.Entry(@class).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.UserId = new SelectList(db.AspNetUsers.Where(x => x.AspNetRoles.Any(g => g.Name.Equals("Lecturer"))), "Id", "Email");
            //ViewBag.Userid = new SelectList(db.AspNetUsers, "Id", "Email", @class.Userid);
            ViewBag.Facultyid = new SelectList(db.FACULTies, "ID", "FACULTYNAME", @class.Facultyid);
            ViewBag.Semesterid = new SelectList(db.SEMESTERs, "ID", "SEMESTER_CODE", @class.Semesterid);
            return View(@class);
        }

        // GET: Classes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Class @class = db.Classes.Find(id);
            if (@class == null)
            {
                return HttpNotFound();
            }
            return View(@class);
        }

        // POST: Classes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Class @class = db.Classes.Find(id);
            db.Classes.Remove(@class);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpPost]
        public JsonResult UploadExcel(Class Classes, HttpPostedFileBase FileUpload)
        {

            List<string> data = new List<string>();
            if (FileUpload != null)
            {
                // tdata.ExecuteCommand("truncate table OtherCompanyAssets");  
                if (FileUpload.ContentType == "application/vnd.ms-excel" || FileUpload.ContentType == "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet")
                {
                    string filename = FileUpload.FileName;
                    string targetpath = Server.MapPath("~/Doc/");
                    FileUpload.SaveAs(targetpath + filename);
                    string pathToExcelFile = targetpath + filename;
                    ExcelFileReader excelFileReader = new ExcelFileReader(pathToExcelFile);
                    List<Class> listClasses = excelFileReader.readClasses(); // Get list Classes from excel  
                    var listClassDb = db.Classes.ToList();
                    foreach (Class @class in listClasses)
                    {
                        if (listClassDb.FirstOrDefault(x => x.ClassCode.Equals(@class.ClassCode)) == null)
                            db.Classes.Add(@class);
                    }
                    db.SaveChanges();
                    //deleting excel file from folder  
                    if ((System.IO.File.Exists(pathToExcelFile)))
                    {
                        System.IO.File.Delete(pathToExcelFile);
                    }
                    // Garbage Collection
                    GC.Collect();
                    GC.WaitForPendingFinalizers();
                    return Json("success", JsonRequestBehavior.AllowGet);
                }
                else
                {
                    //alert message for invalid file format  
                    data.Add("<ul>");
                    data.Add("<li>Only Excel file format is allowed</li>");
                    data.Add("</ul>");
                    data.ToArray();
                    return Json(data, JsonRequestBehavior.AllowGet);
                }
            }
            else
            {
                data.Add("<ul>");
                if (FileUpload == null) data.Add("<li>Please choose Excel file</li>");
                data.Add("</ul>");
                data.ToArray();
                return Json(data, JsonRequestBehavior.AllowGet);
            }
        }





        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebApplication2/WebApplication2/Views/Classes/Create.cshtml
@model WebApplication2.Models.Class

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Class</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.ClassCode, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ClassCode, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ClassCode, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.LessonCode, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.LessonCode, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.LessonCode, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ClassName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ClassName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ClassName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Credit, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Credit, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Credit, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.LessonType, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.LessonType, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.LessonType, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.DayLearn, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.DayLearn, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.DayLearn, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ClassTime, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ClassTime, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ClassTime, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Room, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Room, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Room, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.TotalStudent, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.TotalStudent, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.TotalStudent, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.StartDate, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.EndDate, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.EndDate, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.EndDate, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.TotalWeek, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.TotalWeek, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.TotalWeek, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.NoSession, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.NoSession, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.NoSession, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Scholastic, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Scholastic, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Scholastic, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Semesterid, "Semesterid", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("Semesterid", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Semesterid, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Userid, "Userid", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("Userid", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Userid, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Facultyid, "Facultyid", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("Facultyid", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Facultyid, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

WebApplication2/WebApplication2/Views/Classes/Index.cshtml
@model IEnumerable<WebApplication2.Models.Class>

@{
    ViewBag.Title = "Index";
}

<h2>Class</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
@using (Html.BeginForm("UploadExcel", "Classes", FormMethod.Post, new { enctype = "multipart/form-data", onsubmit = "return myFunction()" }))
{
    <div class="form-horizontal">
        @*<div class="form-group">
            <div class="control-label col-md-2">Download Format:</div>
            <div class="col-md-10">
                <a href="/User/DownloadExcel/"><img src="~/excel.ico" width="25" height="25" title="Download Excel format" alt="excel" /></a>
            </div>
        </div>*@
        <div class="form-group">

            <div class="control-label col-md-2">Excel:</div>
            <div class="col-md-10">
                <input type="file" id="FileUpload" name="FileUpload" class="" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Upload" id="btnSubmit" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">List Class</h6>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.ClassCode)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.ClassName)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.TotalStudent)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.TotalWeek)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.AspNetUser.Email)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.FACULTY.FACULTYNAME)
                        </th>
                        <th>
                            SEMESTERCODE
                        </th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {

                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.ClassCode)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.ClassName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.ClassLists.Count)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.TotalWeek)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.AspNetUser.Email)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.FACULTY.FACULTYNAME)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.SEMESTER.SEMESTER_CODE)
                            </td>
                            <td>
                                <a href="@Url.Action("Index","ATTENDANCE", new { id = item.id })">
                                    <i class="fa fa-id-badge" aria-hidden="true"></i>
                                </a> |
                                <a href="@Url.Action("Index","ClassList", new {id = item.id })"><i class="fa fa-users" style="color:black;" aria-hidden="true"></i></a> |
                                <a href="@Url.Action("Edit","Classes", new {id = item.id })">
                                    <i class="fa fa-wrench" aria-hidden="true"></i>
                                </a> |
                                <a href="@Url.Action("Delete","Classes",new {id = item.id })"><i class="fa fa-times" style="color:red;" aria-hidden="true"></i></a>
                            </td>
                        </tr>

                    }
                </tbody>

            </table>
        </div>
    </div>
</div>

WebApplication2/WebApplication2/Views/Classes/Statistics1.cshtml
@model IEnumerable<WebApplication2.Models.Class>
@using WebApplication2.Models
@{
    ViewBag.Title = "Statistics1";
    var NoSessionMax = ViewBag.NoSessionMax;
    var db = new SEP24Team3Entities();
    var semester = db.SEMESTERs.ToList();
}

<h2>Statistics Student Attended each Session of Class</h2>
<form action="@Url.Action("searchBySemester1","Classes")" method="get">
    <span class="text-info font-weight-bold">Semester:</span>
    <select id="semester" name="semesterId" required>
        <optgroup label="Semester"></optgroup>
        <option value="0">All</option>
        @foreach (var sm in semester)
        {
            <option id="optionId" value="@sm.ID">@sm.SEMESTER_CODE</option>
        }
    </select>
    <input type="submit" id="btnFilter" class="btn btn-info" value="Filter" />

</form>
<div class="mt-2">
    <a class="btn btn-success" id="btnExport" href="@Url.Action("ExportToExcelStatistics1","Classes")">Export Excel</a>
</div>
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold">Statistics</h6>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>Class Code</th>
                        <th class="text-center">
                            Class Name
                        </th>
                        @for (int i = 1; i <= NoSessionMax; i++)
                        {
                            <th class="text-center">Buổi @i</th>
                        }
                        @if (NoSessionMax == 0)
                        {
                            <th>No Session in Semester</th>
                        }


                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.ClassCode</td>
                            <td>@item.ClassName</td>

                            @for (int i = 1; i <= item.NoSession; i++)
                            {
                                int count = 0;
                                foreach (var stdCheckin in item.ATTENDANCEs)
                                {
                                    var test = stdCheckin.SessionName.Substring(5);
                                    if (stdCheckin.STATUS == true && stdCheckin.SessionName.Substring(5).Equals(i.ToString()))
                                    {

                                        count++;
                                    }
                                }
                                <td>@count/@item.ClassLists.Count</td>
                            }
                            @for (int? j = item.NoSession + 1; j <= NoSessionMax; j++)
                            {
                                <td style="background-color:gray;"></td>
                            }
                            @if (item.NoSession == null)
                            {
                                for (int i = 1; i <= NoSessionMax; i++)
                                {
                                    <td style="background-color:gray;"></td>
                                }
                                if (NoSessionMax == 0)
                                {
                                    <td style="background-color:gray;"></td>
                                }
                            }

                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>
<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script>
    //const btnFilter = document.getElementById('btnFilter');
    //var semester = document.getElementById('semester');
    //const btnExport = document.getElementById('btnExport');

    //$(document).ready(function () {
    //    $('#btnFilter').click(function () {
    //        var semesterId = semester.value;
    //        var semesterCode = semester.options[semester.selectedIndex].text;
    //        var textSemester = `Export Excel Semester ${semesterCode}`;
    //        $.ajax({
    //            url: '/Classes/searchBySemester1',
    //            type: 'GET',
    //            data: { semesterId: semesterId },
    //            success: function (res) {
    //                if (semesterId != 0)
    //                    sessionStorage.setItem("semester", textSemester);
    //            }
    //        });
    //    });
    //    if (sessionStorage.getItem("semester")) {
    //        btnExport.innerHTML = sessionStorage.getItem("semester");
    //    } else {
    //        btnExport.innerHTML = "Export Excel";
    //    }

    //    sessionStorage.clear();
    //});

    window.onload = function () {
        var selItem = sessionStorage.getItem("SelItem");
        $('#semester').val(selItem);
        sessionStorage.clear();
    }


        $('#semester').change(function () {
            var selVal = $(this).val();
            sessionStorage.setItem("SelItem", selVal);
        });
        

</script>

WebApplication2/WebApplication2/Views/Classes/Statistics2.cshtml
@model IEnumerable<WebApplication2.Models.Class>
@using WebApplication2.Models
@{
    ViewBag.Title = "Statistics2";
    var db = new SEP24Team3Entities();
    var studentInClass = db.ClassLists.ToList();
    var atd = db.ATTENDANCEs.ToList();
    var semester = db.SEMESTERs.ToList();
    var semesterId = ViewBag.Semester_Id as SEMESTER;
}

<h2>Statistics Students Absent</h2>
<form action="@Url.Action("searchBySemester2","Classes")" method="get">
    <span class="text-info font-weight-bold">Semester:</span>
    <select id="semester" name="semesterId" required>
        <optgroup label="Semester"></optgroup>
        <option value="0">All</option>
        @foreach (var sm in semester)
        {
            <option id="@sm.ID" value="@sm.ID">@sm.SEMESTER_CODE</option>            
        }
    </select>
    <input type="submit" id="btnFilter" class="btn btn-info" value="Filter" />
    
</form>   
<div class="mt-2">
    <a id="btnExport" class="btn btn-success" href="@Url.Action("ExportToExcelStatistics2","Classes")">Export Excel</a>
</div>
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold">Statistics</h6>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>Class Code</th>
                        <th>Class Name</th>
                        <th>Student Name</th>
                        <th>No.Session Absent</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        if (item.NoSession != null)
                        {
                            foreach (var std in studentInClass.Where(x => x.Classid == item.id))
                            {
                                int count = 0;
                                <tr>
                                    <th>@std.Class.ClassCode</th>
                                    <th>@std.Class.ClassName</th>
                                    <td>@std.Student.Fullname</td>

                                    @foreach (var stdAbsent in atd.Where(x => x.ClassId == item.id && x.StudentId == std.Studentid))
                                    {

                                        if (stdAbsent.STATUS == null || stdAbsent.STATUS == false)
                                        {
                                            count++;
                                        }
                                    }
                                    <td>@count/@item.NoSession</td>
                                </tr>
                            }
                        }
                       
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script>
    //const btnFilter = document.getElementById('btnFilter');
    //var semester = document.getElementById('semester');
    //const btnExport = document.getElementById('btnExport');

    //$(document).ready(function () {
    //    var semestercode = $('#optionId').val();
    //    $('#btnFilter').click(function () {
    //        var semesterId = semester.value;
    //        var semesterCode = semester.options[semester.selectedIndex].text;
    //        var textSemester = `Export Excel Semester ${semesterCode}`;
    //        $.ajax({
    //            url: '/Classes/searchBySemester2',
    //            type: 'GET',
    //            data: { semesterId: semesterId },
    //            success: function (res) {
    //                if (semesterId != 0)
    //                sessionStorage.setItem("semester", textSemester);       
    //            }
    //        });
    //    });
    //    if (sessionStorage.getItem("semester")) {
    //        btnExport.innerHTML = sessionStorage.getItem("semester");
    //    } else {
    //        btnExport.innerHTML = "Export Excel";
    //    }
        
    //    sessionStorage.clear();
    //}); 

    window.onload = function () {
        var selItem = sessionStorage.getItem("SelItem2");
        $('#semester').val(selItem);
        sessionStorage.clear();
    }


    $('#semester').change(function () {
        var selVal = $(this).val();
        sessionStorage.setItem("SelItem2", selVal);
    });
</script>